# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roboclaw_msgs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13roboclaw_msgs.proto\x12\rroboclaw_msgs\"/\n\x04Move\x12\x12\n\nleft_motor\x18\x01 \x01(\x05\x12\x13\n\x0bright_motor\x18\x02 \x01(\x05\"\xea\x01\n\x0cMovePosition\x12\x12\n\nleft_speed\x18\x01 \x01(\x05\x12\x19\n\x11left_acceleration\x18\x02 \x01(\x05\x12\x19\n\x11left_deceleration\x18\x03 \x01(\x05\x12\x15\n\rleft_distance\x18\x04 \x01(\x05\x12\x13\n\x0bright_speed\x18\x05 \x01(\x05\x12\x1a\n\x12right_acceleration\x18\x06 \x01(\x05\x12\x1a\n\x12right_deceleration\x18\x07 \x01(\x05\x12\x16\n\x0eright_distance\x18\x08 \x01(\x05\x12\x14\n\x0c\x63lear_buffer\x18\t \x01(\x08\"b\n\nMoveStatus\x12\x14\n\x0cleft_encoder\x18\x01 \x01(\x05\x12\x12\n\nleft_speed\x18\x02 \x01(\x05\x12\x15\n\rright_encoder\x18\x03 \x01(\x05\x12\x13\n\x0bright_speed\x18\x04 \x01(\x05\"\x1d\n\rRequestStatus\x12\x0c\n\x04time\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'roboclaw_msgs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVE._serialized_start=38
  _MOVE._serialized_end=85
  _MOVEPOSITION._serialized_start=88
  _MOVEPOSITION._serialized_end=322
  _MOVESTATUS._serialized_start=324
  _MOVESTATUS._serialized_end=422
  _REQUESTSTATUS._serialized_start=424
  _REQUESTSTATUS._serialized_end=453
# @@protoc_insertion_point(module_scope)
